# Generated by Django 5.0.7 on 2024-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
