# Generated by Django 5.0.7 on 2024-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='share_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
